:icons: font
:hardbreaks:
:authors: Tomasz Borek, Paweł Kierat, Marcin Ogorzałek
:copyright: Copyrighted by EPAM Systems
= Helpers

You should share here your solutions to the task about helper classes from JDK (accordingly to the Tomasz's excel).

IMPORTANT: The main package for these solutions should be `com.epam.prejap.ess.helpers`.

TIP: You can add new dependencies and plugins to the `pom.xml` if necessary.

== Goals

. Studying about helpers on your and the other's code.
. Creating a source of the knowledge on the subject that you can come back to.
. Exercising work with shared repository and forks.

== Task

. Fork the repository (button in the upper right corner of the main page).
. Implement your solution to the task given to you by Tomasz during lecture about helpers.
. Create a commit with a meaningful message.
. Push the changes to a remote master branch **on your fork**.
+
NOTE: You don't have to use a feature branch, only `master` is fine.
+
. Create a Pull Request to merge it to `EPAM-Online-Courses/helpers:master`.

[IMPORTANT]
----
YOU WILL NOW BE WORKING ON THE FORKED REPO, NOT ON THIS ONE, BUT ON YOUR GITHUB
COPY OF IT, CALLED THE FORK. WE REPEAT, YOU WILL NOW BE WORKING ON THE FORK.

Commands and task steps to do ON THE FORK. It's to be done ON THE FORK, ok?
NOT HERE, NOT IN YOUR LOCAL REPOSITORY.
----

== Rules

. Your implementation shall not break any of the existing solutions.
. PRs will be accepted ASAP once we see they're demonstrating API assigned to you during the lecture about helpers.
